### ISSUE TITLE
Use function hypot instead of sqrt (dx*.dx+.dy*.dy)

### ISSUE THREAD

**Issue by richardalligier** [ghilesZ/geoml#14]
Hello,
Since OCaml 4.00, there is the function `hypot` in the standard library. It is said to avoid undue overflow or underflow.
It could be used in `Point.distance` and `Vector.magnitude`. In my program, using `hypot` led me to different (and hopefully more precise) results.

Best,
Richard

**Comment by ghilesZ** [comment]
Hi @richardalligier,

thanks for the remark, i'm pushing a fix right now.

Best,
Ghiles.
