### ISSUE TITLE
Why no voronoi diagram ?

### ISSUE THREAD

**Issue by CharlesHD** [ghilesZ/geoml#3]
Whoa, GeoML is amazing! I use it for all my ocaml geometry problems. But I'm so sad I can't directly get voronoi diagram :'( Have you planned VD for the future of GeoML?

**Comment by ghilesZ** [comment]
Hi,
first of all, thank you for using geoml!
We are currently solving some bezier issues, but don't worry, soon VD will
be part of geoml's features

2015-10-29 18:28 GMT+01:00 CharlesHD notifications@github.com:
