### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by tbrup** [ghilesZ/geoml#9]
Not sure if this is a pilot error...

After cloning the repo, compiling with make gives these error messages:

dune build src/geoml.cma
Entering directory '/Users/thomasbrupbacher/temp'
File "geoml/src/constraint.mli", line 7, characters 18-24:
7 | type t = private  Line.t * comp
                      ^^^^^^
Error: Unbound type constructor Line.t
File "geoml/src/polygon.mli", line 5, characters 17-24:
5 | type t = private Point.t list
                     ^^^^^^^
Error: Unbound type constructor Point.t
File "geoml/src/curve.ml", line 4, characters 11-18:
4 |   type t = Point.t * Point.t * Point.t
               ^^^^^^^
Error: Unbound type constructor Point.t
make: *** [build] Error 1

Being relatively new to Ocaml, I have no idea how to fix this.

Environment:
MacOS 10.14.x
Ocaml 4.08.1

**Comment by ghilesZ** [comment]
Yes some unfinished implementation have been pushed in a barbaric style on master. 
commit 3e8fb4f91788e01f761be03db9947b83066d74fd should fix this.
Can you confirm it so i close the issue?
Thanx.

**Comment by tbrup** [comment]
Just tried it and it does work.

Thanks!

**Comment by ghilesZ** [comment]
ok thanks
